- id: '1716162838350'
  alias: Turn on pond filtration in the morning
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition: []
  action:
  - type: turn_on
    device_id: 980747b6bfd7ff908d5f247c1f8f2670
    entity_id: 238a78a4c5b45c426c88587cb255fa8e
    domain: switch
  mode: single
- id: '1716162867316'
  alias: Turn off pond filtration in the afternoon
  description: ''
  trigger:
  - platform: time
    at: '16:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 980747b6bfd7ff908d5f247c1f8f2670
    entity_id: 238a78a4c5b45c426c88587cb255fa8e
    domain: switch
  mode: single
- id: '1717940105957'
  alias: Turn on boiler in the morning
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - type: turn_on
    device_id: c92516ce4e11f70523c2a8ce48edd9d0
    entity_id: b2f520ed5556989e534330361c6099bb
    domain: switch
  mode: single
- id: '1717940169228'
  alias: Turn off boiler in the evening
  description: ''
  trigger:
  - platform: time
    at: '18:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: c92516ce4e11f70523c2a8ce48edd9d0
    entity_id: b2f520ed5556989e534330361c6099bb
    domain: switch
  mode: single
