- id: '1716162838350'
  alias: Turn on lake power in the morning
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition: []
  action:
  - type: turn_on
    device_id: 9ae2908dbc928a0f46055c28f18d6e34
    entity_id: 5f67031077c56a75d034874ef6a8e18d
    domain: switch
  mode: single
- id: '1716162867316'
  alias: Turn off lake power in the afternoon
  description: ''
  trigger:
  - platform: time
    at: '16:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 9ae2908dbc928a0f46055c28f18d6e34
    entity_id: 5f67031077c56a75d034874ef6a8e18d
    domain: switch
  mode: single
